### ISSUE TITLE
Flash is not installed

### ISSUE THREAD

**Issue by eirsyl** [webkom/chewie#76]
TypeError: undefined is not a function
    at allFailed (/home/chewie/chewie/node_modules/passport/lib/middleware/authenticate.js:111:15)
    at attempt (/home/chewie/chewie/node_modules/passport/lib/middleware/authenticate.js:160:28)
    at Strategy.strategy.fail (/home/chewie/chewie/node_modules/passport/lib/middleware/authenticate.js:277:9)
    at verified (/home/chewie/chewie/node_modules/passport-abakus/node_modules/passport-local/lib/strategy.js:82:30)
    at Request._callback (/home/chewie/chewie/node_modules/passport-abakus/index.js:51:21)
    at Request.self.callback (/home/chewie/chewie/node_modules/request/request.js:236:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (/home/chewie/chewie/node_modules/request/request.js:1142:14)
    at Request.emit (events.js:129:20)
    at IncomingMessage.<anonymous> (/home/chewie/chewie/node_modules/request/request.js:1096:12)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)
error: Forever detected script exited with code: 1
error: Script restart attempt #1
/home/chewie/chewie/node_modules/passport/lib/middleware/authenticate.js:111
          req.flash(type, msg);
              ^
TypeError: undefined is not a function
    at allFailed (/home/chewie/chewie/node_modules/passport/lib/middleware/authenticate.js:111:15)
    at attempt (/home/chewie/chewie/node_modules/passport/lib/middleware/authenticate.js:160:28)
    at Strategy.strategy.fail (/home/chewie/chewie/node_modules/passport/lib/middleware/authenticate.js:277:9)
    at verified (/home/chewie/chewie/node_modules/passport-abakus/node_modules/passport-local/lib/strategy.js:82:30)
    at Request._callback (/home/chewie/chewie/node_modules/passport-abakus/index.js:51:21)
    at Request.self.callback (/home/chewie/chewie/node_modules/request/request.js:236:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (/home/chewie/chewie/node_modules/request/request.js:1142:14)
    at Request.emit (events.js:129:20)
    at IncomingMessage.<anonymous> (/home/chewie/chewie/node_modules/request/request.js:1096:12)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)
error: Forever detected script exited with code: 1

**Comment by ekmartin** [comment]
Closing in favor of https://github.com/webkom/passport-abakus/issues/10
